site_name: crypto
theme: ponylang
markdown_extensions:
- markdown.extensions.toc:
    permalink: true
nav:
- crypto: index.md
- package crypto:
  - Package: "crypto--index.md"
  - interface HashFn: "crypto-HashFn.md"
  - primitive MD4: "crypto-MD4.md"
  - primitive MD5: "crypto-MD5.md"
  - primitive RIPEMD160: "crypto-RIPEMD160.md"
  - primitive SHA1: "crypto-SHA1.md"
  - primitive SHA224: "crypto-SHA224.md"
  - primitive SHA256: "crypto-SHA256.md"
  - primitive SHA384: "crypto-SHA384.md"
  - primitive SHA512: "crypto-SHA512.md"
  - primitive ToHexString: "crypto-ToHexString.md"
  - class Digest: "crypto-Digest.md"
  - primitive ConstantTimeCompare: "crypto-ConstantTimeCompare.md"
- package builtin:
  - Package: "builtin--index.md"
  - primitive U8: "builtin-U8.md"
  - primitive U16: "builtin-U16.md"
  - primitive U32: "builtin-U32.md"
  - primitive U64: "builtin-U64.md"
  - primitive ULong: "builtin-ULong.md"
  - primitive USize: "builtin-USize.md"
  - primitive U128: "builtin-U128.md"
  - type Unsigned: "builtin-Unsigned.md"
  - interface Stringable: "builtin-Stringable.md"
  - class String: "builtin-String.md"
  - class StringBytes: "builtin-StringBytes.md"
  - class StringRunes: "builtin-StringRunes.md"
  - interface InputNotify: "builtin-InputNotify.md"
  - interface InputStream: "builtin-InputStream.md"
  - actor Stdin: "builtin-Stdin.md"
  - type ByteSeq: "builtin-ByteSeq.md"
  - interface ByteSeqIter: "builtin-ByteSeqIter.md"
  - interface OutStream: "builtin-OutStream.md"
  - actor StdStream: "builtin-StdStream.md"
  - interface SourceLoc: "builtin-SourceLoc.md"
  - primitive I8: "builtin-I8.md"
  - primitive I16: "builtin-I16.md"
  - primitive I32: "builtin-I32.md"
  - primitive I64: "builtin-I64.md"
  - primitive ILong: "builtin-ILong.md"
  - primitive ISize: "builtin-ISize.md"
  - primitive I128: "builtin-I128.md"
  - type Signed: "builtin-Signed.md"
  - interface Seq: "builtin-Seq.md"
  - trait Real: "builtin-Real.md"
  - trait Integer: "builtin-Integer.md"
  - trait SignedInteger: "builtin-SignedInteger.md"
  - trait UnsignedInteger: "builtin-UnsignedInteger.md"
  - trait FloatingPoint: "builtin-FloatingPoint.md"
  - type Number: "builtin-Number.md"
  - type Int: "builtin-Int.md"
  - interface ReadSeq: "builtin-ReadSeq.md"
  - interface ReadElement: "builtin-ReadElement.md"
  - struct Pointer: "builtin-Pointer.md"
  - primitive Platform: "builtin-Platform.md"
  - primitive None: "builtin-None.md"
  - struct MaybePointer: "builtin-MaybePointer.md"
  - interface Iterator: "builtin-Iterator.md"
  - primitive F32: "builtin-F32.md"
  - primitive F64: "builtin-F64.md"
  - type Float: "builtin-Float.md"
  - class Env: "builtin-Env.md"
  - primitive DoNotOptimise: "builtin-DoNotOptimise.md"
  - interface DisposableActor: "builtin-DisposableActor.md"
  - primitive Less: "builtin-Less.md"
  - primitive Equal: "builtin-Equal.md"
  - primitive Greater: "builtin-Greater.md"
  - type Compare: "builtin-Compare.md"
  - interface HasEq: "builtin-HasEq.md"
  - interface Equatable: "builtin-Equatable.md"
  - interface Comparable: "builtin-Comparable.md"
  - primitive Bool: "builtin-Bool.md"
  - type AsioEventID: "builtin-AsioEventID.md"
  - interface AsioEventNotify: "builtin-AsioEventNotify.md"
  - primitive AsioEvent: "builtin-AsioEvent.md"
  - class Array: "builtin-Array.md"
  - class ArrayKeys: "builtin-ArrayKeys.md"
  - class ArrayValues: "builtin-ArrayValues.md"
  - class ArrayPairs: "builtin-ArrayPairs.md"
  - interface Any: "builtin-Any.md"
  - primitive AmbientAuth: "builtin-AmbientAuth.md"
- package collections:
  - Package: "collections--index.md"
  - primitive Sort: "collections-Sort.md"
  - type Set: "collections-Set.md"
  - type SetIs: "collections-SetIs.md"
  - class HashSet: "collections-HashSet.md"
  - class SetValues: "collections-SetValues.md"
  - class RingBuffer: "collections-RingBuffer.md"
  - class Reverse: "collections-Reverse.md"
  - class Range: "collections-Range.md"
  - type Map: "collections-Map.md"
  - type MapIs: "collections-MapIs.md"
  - class HashMap: "collections-HashMap.md"
  - class MapKeys: "collections-MapKeys.md"
  - class MapValues: "collections-MapValues.md"
  - class MapPairs: "collections-MapPairs.md"
  - class ListNode: "collections-ListNode.md"
  - class List: "collections-List.md"
  - class ListNodes: "collections-ListNodes.md"
  - class ListValues: "collections-ListValues.md"
  - type MinHeap: "collections-MinHeap.md"
  - type MaxHeap: "collections-MaxHeap.md"
  - class BinaryHeap: "collections-BinaryHeap.md"
  - type BinaryHeapPriority: "collections-BinaryHeapPriority.md"
  - primitive MinHeapPriority: "collections-MinHeapPriority.md"
  - primitive MaxHeapPriority: "collections-MaxHeapPriority.md"
  - interface Hashable: "collections-Hashable.md"
  - interface Hashable64: "collections-Hashable64.md"
  - interface HashFunction: "collections-HashFunction.md"
  - interface HashFunction64: "collections-HashFunction64.md"
  - primitive HashEq: "collections-HashEq.md"
  - primitive HashEq64: "collections-HashEq64.md"
  - primitive HashIs: "collections-HashIs.md"
  - primitive HashByteSeq: "collections-HashByteSeq.md"
  - interface Flag: "collections-Flag.md"
  - class Flags: "collections-Flags.md"
- package format:
  - Package: "format--index.md"
  - trait PrefixSpec: "format-PrefixSpec.md"
  - primitive PrefixDefault: "format-PrefixDefault.md"
  - primitive PrefixSpace: "format-PrefixSpace.md"
  - primitive PrefixSign: "format-PrefixSign.md"
  - type PrefixNumber: "format-PrefixNumber.md"
  - trait FormatSpec: "format-FormatSpec.md"
  - primitive FormatDefault: "format-FormatDefault.md"
  - primitive FormatUTF32: "format-FormatUTF32.md"
  - primitive FormatBinary: "format-FormatBinary.md"
  - primitive FormatBinaryBare: "format-FormatBinaryBare.md"
  - primitive FormatOctal: "format-FormatOctal.md"
  - primitive FormatOctalBare: "format-FormatOctalBare.md"
  - primitive FormatHex: "format-FormatHex.md"
  - primitive FormatHexBare: "format-FormatHexBare.md"
  - primitive FormatHexSmall: "format-FormatHexSmall.md"
  - primitive FormatHexSmallBare: "format-FormatHexSmallBare.md"
  - type FormatInt: "format-FormatInt.md"
  - primitive FormatExp: "format-FormatExp.md"
  - primitive FormatExpLarge: "format-FormatExpLarge.md"
  - primitive FormatFix: "format-FormatFix.md"
  - primitive FormatFixLarge: "format-FormatFixLarge.md"
  - primitive FormatGeneral: "format-FormatGeneral.md"
  - primitive FormatGeneralLarge: "format-FormatGeneralLarge.md"
  - type FormatFloat: "format-FormatFloat.md"
  - primitive Format: "format-Format.md"
  - primitive AlignLeft: "format-AlignLeft.md"
  - primitive AlignRight: "format-AlignRight.md"
  - primitive AlignCenter: "format-AlignCenter.md"
  - type Align: "format-Align.md"
- package ponytest:
  - Package: "ponytest--index.md"
  - trait UnitTest: "ponytest-UnitTest.md"
  - trait TestList: "ponytest-TestList.md"
  - interface ITest: "ponytest-ITest.md"
  - class TestHelper: "ponytest-TestHelper.md"
  - actor PonyTest: "ponytest-PonyTest.md"
- package random:
  - Package: "random--index.md"
  - class XorShift128Plus: "random-XorShift128Plus.md"
  - class XorOshiro128Plus: "random-XorOshiro128Plus.md"
  - class XorOshiro128StarStar: "random-XorOshiro128StarStar.md"
  - class SplitMix64: "random-SplitMix64.md"
  - type Rand: "random-Rand.md"
  - trait Random: "random-Random.md"
  - class MT: "random-MT.md"
  - class Dice: "random-Dice.md"
- package time:
  - Package: "time--index.md"
  - actor Timers: "time-Timers.md"
  - interface TimerNotify: "time-TimerNotify.md"
  - class Timer: "time-Timer.md"
  - primitive Time: "time-Time.md"
  - class PosixDate: "time-PosixDate.md"
  - primitive Nanos: "time-Nanos.md"
- source:
  - hash_fn.pony : "src/crypto/hash_fn.md" 
  - digest.pony : "src/crypto/digest.md" 
  - constant_time_compare.pony : "src/crypto/constant_time_compare.md" 
  - unsigned.pony : "src/builtin/unsigned.md" 
  - stringable.pony : "src/builtin/stringable.md" 
  - string.pony : "src/builtin/string.md" 
  - stdin.pony : "src/builtin/stdin.md" 
  - std_stream.pony : "src/builtin/std_stream.md" 
  - source_loc.pony : "src/builtin/source_loc.md" 
  - signed.pony : "src/builtin/signed.md" 
  - seq.pony : "src/builtin/seq.md" 
  - real.pony : "src/builtin/real.md" 
  - read_seq.pony : "src/builtin/read_seq.md" 
  - pointer.pony : "src/builtin/pointer.md" 
  - platform.pony : "src/builtin/platform.md" 
  - none.pony : "src/builtin/none.md" 
  - maybe_pointer.pony : "src/builtin/maybe_pointer.md" 
  - iterator.pony : "src/builtin/iterator.md" 
  - float.pony : "src/builtin/float.md" 
  - env.pony : "src/builtin/env.md" 
  - do_not_optimise.pony : "src/builtin/do_not_optimise.md" 
  - disposable_actor.pony : "src/builtin/disposable_actor.md" 
  - compare.pony : "src/builtin/compare.md" 
  - bool.pony : "src/builtin/bool.md" 
  - asio_event.pony : "src/builtin/asio_event.md" 
  - array.pony : "src/builtin/array.md" 
  - any.pony : "src/builtin/any.md" 
  - ambient_auth.pony : "src/builtin/ambient_auth.md" 
  - sort.pony : "src/collections/sort.md" 
  - set.pony : "src/collections/set.md" 
  - ring_buffer.pony : "src/collections/ring_buffer.md" 
  - reverse.pony : "src/collections/reverse.md" 
  - range.pony : "src/collections/range.md" 
  - map.pony : "src/collections/map.md" 
  - list_node.pony : "src/collections/list_node.md" 
  - list.pony : "src/collections/list.md" 
  - heap.pony : "src/collections/heap.md" 
  - hashable.pony : "src/collections/hashable.md" 
  - flag.pony : "src/collections/flag.md" 
  - prefix_spec.pony : "src/format/prefix_spec.md" 
  - format_spec.pony : "src/format/format_spec.md" 
  - format.pony : "src/format/format.md" 
  - align.pony : "src/format/align.md" 
  - unit_test.pony : "src/ponytest/unit_test.md" 
  - test_list.pony : "src/ponytest/test_list.md" 
  - test_helper.pony : "src/ponytest/test_helper.md" 
  - pony_test.pony : "src/ponytest/pony_test.md" 
  - xorshift.pony : "src/random/xorshift.md" 
  - xoroshiro.pony : "src/random/xoroshiro.md" 
  - splitmix64.pony : "src/random/splitmix64.md" 
  - random.pony : "src/random/random.md" 
  - mt.pony : "src/random/mt.md" 
  - dice.pony : "src/random/dice.md" 
  - timers.pony : "src/time/timers.md" 
  - timer_notify.pony : "src/time/timer_notify.md" 
  - timer.pony : "src/time/timer.md" 
  - time.pony : "src/time/time.md" 
  - posix_date.pony : "src/time/posix_date.md" 
  - nanos.pony : "src/time/nanos.md" 
