site_name: semver
theme: ponylang
markdown_extensions:
- markdown.extensions.toc:
    permalink: true
nav:
- semver: index.md
- package semver:
  - Package: "semver--index.md"
- package buffered:
  - Package: "buffered--index.md"
  - class Writer: "buffered-Writer.md"
  - class Reader: "buffered-Reader.md"
- package builtin:
  - Package: "builtin--index.md"
  - primitive U8: "builtin-U8.md"
  - primitive U16: "builtin-U16.md"
  - primitive U32: "builtin-U32.md"
  - primitive U64: "builtin-U64.md"
  - primitive ULong: "builtin-ULong.md"
  - primitive USize: "builtin-USize.md"
  - primitive U128: "builtin-U128.md"
  - type Unsigned: "builtin-Unsigned.md"
  - interface Stringable: "builtin-Stringable.md"
  - class String: "builtin-String.md"
  - class StringBytes: "builtin-StringBytes.md"
  - class StringRunes: "builtin-StringRunes.md"
  - interface InputNotify: "builtin-InputNotify.md"
  - interface InputStream: "builtin-InputStream.md"
  - actor Stdin: "builtin-Stdin.md"
  - type ByteSeq: "builtin-ByteSeq.md"
  - interface ByteSeqIter: "builtin-ByteSeqIter.md"
  - interface OutStream: "builtin-OutStream.md"
  - actor StdStream: "builtin-StdStream.md"
  - interface SourceLoc: "builtin-SourceLoc.md"
  - primitive I8: "builtin-I8.md"
  - primitive I16: "builtin-I16.md"
  - primitive I32: "builtin-I32.md"
  - primitive I64: "builtin-I64.md"
  - primitive ILong: "builtin-ILong.md"
  - primitive ISize: "builtin-ISize.md"
  - primitive I128: "builtin-I128.md"
  - type Signed: "builtin-Signed.md"
  - interface Seq: "builtin-Seq.md"
  - struct RuntimeOptions: "builtin-RuntimeOptions.md"
  - trait Real: "builtin-Real.md"
  - trait Integer: "builtin-Integer.md"
  - trait SignedInteger: "builtin-SignedInteger.md"
  - trait UnsignedInteger: "builtin-UnsignedInteger.md"
  - trait FloatingPoint: "builtin-FloatingPoint.md"
  - type Number: "builtin-Number.md"
  - type Int: "builtin-Int.md"
  - interface ReadSeq: "builtin-ReadSeq.md"
  - interface ReadElement: "builtin-ReadElement.md"
  - struct Pointer: "builtin-Pointer.md"
  - primitive Platform: "builtin-Platform.md"
  - struct NullablePointer: "builtin-NullablePointer.md"
  - primitive None: "builtin-None.md"
  - interface Iterator: "builtin-Iterator.md"
  - primitive F32: "builtin-F32.md"
  - primitive F64: "builtin-F64.md"
  - type Float: "builtin-Float.md"
  - class Env: "builtin-Env.md"
  - primitive DoNotOptimise: "builtin-DoNotOptimise.md"
  - interface DisposableActor: "builtin-DisposableActor.md"
  - primitive Less: "builtin-Less.md"
  - primitive Equal: "builtin-Equal.md"
  - primitive Greater: "builtin-Greater.md"
  - type Compare: "builtin-Compare.md"
  - interface HasEq: "builtin-HasEq.md"
  - interface Equatable: "builtin-Equatable.md"
  - interface Comparable: "builtin-Comparable.md"
  - primitive Bool: "builtin-Bool.md"
  - type AsioEventID: "builtin-AsioEventID.md"
  - interface AsioEventNotify: "builtin-AsioEventNotify.md"
  - primitive AsioEvent: "builtin-AsioEvent.md"
  - class Array: "builtin-Array.md"
  - class ArrayKeys: "builtin-ArrayKeys.md"
  - class ArrayValues: "builtin-ArrayValues.md"
  - class ArrayPairs: "builtin-ArrayPairs.md"
  - interface Any: "builtin-Any.md"
  - primitive AmbientAuth: "builtin-AmbientAuth.md"
- package capsicum:
  - Package: "capsicum--index.md"
  - type CapRights: "capsicum-CapRights.md"
  - class CapRights0: "capsicum-CapRights0.md"
  - primitive Cap: "capsicum-Cap.md"
- package collections:
  - Package: "collections--index.md"
  - primitive Sort: "collections-Sort.md"
  - type Set: "collections-Set.md"
  - type SetIs: "collections-SetIs.md"
  - class HashSet: "collections-HashSet.md"
  - class SetValues: "collections-SetValues.md"
  - class RingBuffer: "collections-RingBuffer.md"
  - class Reverse: "collections-Reverse.md"
  - class Range: "collections-Range.md"
  - type Map: "collections-Map.md"
  - type MapIs: "collections-MapIs.md"
  - class HashMap: "collections-HashMap.md"
  - class MapKeys: "collections-MapKeys.md"
  - class MapValues: "collections-MapValues.md"
  - class MapPairs: "collections-MapPairs.md"
  - class ListNode: "collections-ListNode.md"
  - class List: "collections-List.md"
  - class ListNodes: "collections-ListNodes.md"
  - class ListValues: "collections-ListValues.md"
  - type MinHeap: "collections-MinHeap.md"
  - type MaxHeap: "collections-MaxHeap.md"
  - class BinaryHeap: "collections-BinaryHeap.md"
  - type BinaryHeapPriority: "collections-BinaryHeapPriority.md"
  - primitive MinHeapPriority: "collections-MinHeapPriority.md"
  - primitive MaxHeapPriority: "collections-MaxHeapPriority.md"
  - interface Hashable: "collections-Hashable.md"
  - interface Hashable64: "collections-Hashable64.md"
  - interface HashFunction: "collections-HashFunction.md"
  - interface HashFunction64: "collections-HashFunction64.md"
  - primitive HashEq: "collections-HashEq.md"
  - primitive HashEq64: "collections-HashEq64.md"
  - primitive HashIs: "collections-HashIs.md"
  - primitive HashByteSeq: "collections-HashByteSeq.md"
  - interface Flag: "collections-Flag.md"
  - class Flags: "collections-Flags.md"
- package files:
  - Package: "files--index.md"
  - primitive Path: "files-Path.md"
  - actor FileStream: "files-FileStream.md"
  - interface WalkHandler: "files-WalkHandler.md"
  - class FilePath: "files-FilePath.md"
  - class FileMode: "files-FileMode.md"
  - class FileLines: "files-FileLines.md"
  - class FileInfo: "files-FileInfo.md"
  - primitive FileCreate: "files-FileCreate.md"
  - primitive FileChmod: "files-FileChmod.md"
  - primitive FileChown: "files-FileChown.md"
  - primitive FileLink: "files-FileLink.md"
  - primitive FileLookup: "files-FileLookup.md"
  - primitive FileMkdir: "files-FileMkdir.md"
  - primitive FileRead: "files-FileRead.md"
  - primitive FileRemove: "files-FileRemove.md"
  - primitive FileRename: "files-FileRename.md"
  - primitive FileSeek: "files-FileSeek.md"
  - primitive FileStat: "files-FileStat.md"
  - primitive FileSync: "files-FileSync.md"
  - primitive FileTime: "files-FileTime.md"
  - primitive FileTruncate: "files-FileTruncate.md"
  - primitive FileWrite: "files-FileWrite.md"
  - primitive FileExec: "files-FileExec.md"
  - type FileCaps: "files-FileCaps.md"
  - primitive FileOK: "files-FileOK.md"
  - primitive FileError: "files-FileError.md"
  - primitive FileEOF: "files-FileEOF.md"
  - primitive FileBadFileNumber: "files-FileBadFileNumber.md"
  - primitive FileExists: "files-FileExists.md"
  - primitive FilePermissionDenied: "files-FilePermissionDenied.md"
  - type FileErrNo: "files-FileErrNo.md"
  - primitive CreateFile: "files-CreateFile.md"
  - primitive OpenFile: "files-OpenFile.md"
  - class File: "files-File.md"
  - class Directory: "files-Directory.md"
- package ponytest:
  - Package: "ponytest--index.md"
  - trait UnitTest: "ponytest-UnitTest.md"
  - trait TestList: "ponytest-TestList.md"
  - interface ITest: "ponytest-ITest.md"
  - class TestHelper: "ponytest-TestHelper.md"
  - actor PonyTest: "ponytest-PonyTest.md"
- package promises:
  - Package: "promises--index.md"
  - actor Promise: "promises-Promise.md"
  - primitive Promises: "promises-Promises.md"
  - interface Fulfill: "promises-Fulfill.md"
  - interface Reject: "promises-Reject.md"
  - class FulfillIdentity: "promises-FulfillIdentity.md"
  - class RejectAlways: "promises-RejectAlways.md"
- package random:
  - Package: "random--index.md"
  - class XorShift128Plus: "random-XorShift128Plus.md"
  - class XorOshiro128Plus: "random-XorOshiro128Plus.md"
  - class XorOshiro128StarStar: "random-XorOshiro128StarStar.md"
  - class SplitMix64: "random-SplitMix64.md"
  - type Rand: "random-Rand.md"
  - trait Random: "random-Random.md"
  - class MT: "random-MT.md"
  - class Dice: "random-Dice.md"
- package semver/../../range:
  - Package: "semver-..-..-range--index.md"
  - primitive RangeBoundsAreEqual: "semver-..-..-range-RangeBoundsAreEqual.md"
  - type RangeBound: "semver-..-..-range-RangeBound.md"
  - class Range: "semver-..-..-range-Range.md"
- package semver/../../solver:
  - Package: "semver-..-..-solver--index.md"
  - class Solver: "semver-..-..-solver-Solver.md"
  - class Result: "semver-..-..-solver-Result.md"
  - class InMemArtifactSource: "semver-..-..-solver-InMemArtifactSource.md"
  - class Constraint: "semver-..-..-solver-Constraint.md"
  - interface ArtifactSource: "semver-..-..-solver-ArtifactSource.md"
  - class Artifact: "semver-..-..-solver-Artifact.md"
- package semver/../utils:
  - Package: "semver-..-utils--index.md"
  - primitive Strings: "semver-..-utils-Strings.md"
  - class EmptyIterator: "semver-..-utils-EmptyIterator.md"
  - class ZipIterator: "semver-..-utils-ZipIterator.md"
  - interface ComparableMixin: "semver-..-utils-ComparableMixin.md"
- package semver/../version:
  - Package: "semver-..-version--index.md"
  - class Version: "semver-..-version-Version.md"
  - primitive ValidateFields: "semver-..-version-ValidateFields.md"
  - type PreReleaseField: "semver-..-version-PreReleaseField.md"
  - primitive ParseVersion: "semver-..-version-ParseVersion.md"
  - primitive Consts: "semver-..-version-Consts.md"
  - primitive CompareVersions: "semver-..-version-CompareVersions.md"
- package semver/./test/range:
  - Package: "semver-.-test-range--index.md"
- package semver/./test/solver:
  - Package: "semver-.-test-solver--index.md"
  - class Scenario: "semver-.-test-solver-Scenario.md"
- package semver/./test/utils:
  - Package: "semver-.-test-utils--index.md"
  - class AlwaysComparesAs: "semver-.-test-utils-AlwaysComparesAs.md"
- package semver/./test/version:
  - Package: "semver-.-test-version--index.md"
- package signals:
  - Package: "signals--index.md"
  - interface SignalNotify: "signals-SignalNotify.md"
  - primitive SignalRaise: "signals-SignalRaise.md"
  - actor SignalHandler: "signals-SignalHandler.md"
  - primitive Sig: "signals-Sig.md"
- package strings:
  - Package: "strings--index.md"
  - primitive CommonPrefix: "strings-CommonPrefix.md"
- package term:
  - Package: "term--index.md"
  - interface ReadlineNotify: "term-ReadlineNotify.md"
  - class Readline: "term-Readline.md"
  - actor ANSITerm: "term-ANSITerm.md"
  - interface ANSINotify: "term-ANSINotify.md"
  - primitive ANSI: "term-ANSI.md"
- package time:
  - Package: "time--index.md"
  - actor Timers: "time-Timers.md"
  - interface TimerNotify: "time-TimerNotify.md"
  - class Timer: "time-Timer.md"
  - primitive Time: "time-Time.md"
  - class PosixDate: "time-PosixDate.md"
  - primitive Nanos: "time-Nanos.md"
- source:
  - writer.pony : "src/buffered/writer.md" 
  - reader.pony : "src/buffered/reader.md" 
  - unsigned.pony : "src/builtin/unsigned.md" 
  - stringable.pony : "src/builtin/stringable.md" 
  - string.pony : "src/builtin/string.md" 
  - stdin.pony : "src/builtin/stdin.md" 
  - std_stream.pony : "src/builtin/std_stream.md" 
  - source_loc.pony : "src/builtin/source_loc.md" 
  - signed.pony : "src/builtin/signed.md" 
  - seq.pony : "src/builtin/seq.md" 
  - runtime_options.pony : "src/builtin/runtime_options.md" 
  - real.pony : "src/builtin/real.md" 
  - read_seq.pony : "src/builtin/read_seq.md" 
  - pointer.pony : "src/builtin/pointer.md" 
  - platform.pony : "src/builtin/platform.md" 
  - nullable_pointer.pony : "src/builtin/nullable_pointer.md" 
  - none.pony : "src/builtin/none.md" 
  - iterator.pony : "src/builtin/iterator.md" 
  - float.pony : "src/builtin/float.md" 
  - env.pony : "src/builtin/env.md" 
  - do_not_optimise.pony : "src/builtin/do_not_optimise.md" 
  - disposable_actor.pony : "src/builtin/disposable_actor.md" 
  - compare.pony : "src/builtin/compare.md" 
  - bool.pony : "src/builtin/bool.md" 
  - asio_event.pony : "src/builtin/asio_event.md" 
  - array.pony : "src/builtin/array.md" 
  - any.pony : "src/builtin/any.md" 
  - ambient_auth.pony : "src/builtin/ambient_auth.md" 
  - cap_rights.pony : "src/capsicum/cap_rights.md" 
  - cap.pony : "src/capsicum/cap.md" 
  - sort.pony : "src/collections/sort.md" 
  - set.pony : "src/collections/set.md" 
  - ring_buffer.pony : "src/collections/ring_buffer.md" 
  - reverse.pony : "src/collections/reverse.md" 
  - range.pony : "src/collections/range.md" 
  - map.pony : "src/collections/map.md" 
  - list_node.pony : "src/collections/list_node.md" 
  - list.pony : "src/collections/list.md" 
  - heap.pony : "src/collections/heap.md" 
  - hashable.pony : "src/collections/hashable.md" 
  - flag.pony : "src/collections/flag.md" 
  - path.pony : "src/files/path.md" 
  - file_stream.pony : "src/files/file_stream.md" 
  - file_path.pony : "src/files/file_path.md" 
  - file_mode.pony : "src/files/file_mode.md" 
  - file_lines.pony : "src/files/file_lines.md" 
  - file_info.pony : "src/files/file_info.md" 
  - file_caps.pony : "src/files/file_caps.md" 
  - file.pony : "src/files/file.md" 
  - directory.pony : "src/files/directory.md" 
  - unit_test.pony : "src/ponytest/unit_test.md" 
  - test_list.pony : "src/ponytest/test_list.md" 
  - test_helper.pony : "src/ponytest/test_helper.md" 
  - pony_test.pony : "src/ponytest/pony_test.md" 
  - promise.pony : "src/promises/promise.md" 
  - fulfill.pony : "src/promises/fulfill.md" 
  - xorshift.pony : "src/random/xorshift.md" 
  - xoroshiro.pony : "src/random/xoroshiro.md" 
  - splitmix64.pony : "src/random/splitmix64.md" 
  - random.pony : "src/random/random.md" 
  - mt.pony : "src/random/mt.md" 
  - dice.pony : "src/random/dice.md" 
  - range_bounds_are_equal.pony : "src/semver-__-__-range/range_bounds_are_equal.md" 
  - range_bound.pony : "src/semver-__-__-range/range_bound.md" 
  - range.pony : "src/semver-__-__-range/range.md" 
  - solver.pony : "src/semver-__-__-solver/solver.md" 
  - result.pony : "src/semver-__-__-solver/result.md" 
  - in_mem_artifact_source.pony : "src/semver-__-__-solver/in_mem_artifact_source.md" 
  - constraint.pony : "src/semver-__-__-solver/constraint.md" 
  - artifact_source.pony : "src/semver-__-__-solver/artifact_source.md" 
  - artifact.pony : "src/semver-__-__-solver/artifact.md" 
  - strings.pony : "src/semver-__-utils/strings.md" 
  - iterators.pony : "src/semver-__-utils/iterators.md" 
  - comparable_mixin.pony : "src/semver-__-utils/comparable_mixin.md" 
  - version.pony : "src/semver-__-version/version.md" 
  - validate_fields.pony : "src/semver-__-version/validate_fields.md" 
  - pre_release_field.pony : "src/semver-__-version/pre_release_field.md" 
  - parse_version.pony : "src/semver-__-version/parse_version.md" 
  - consts.pony : "src/semver-__-version/consts.md" 
  - compare_versions.pony : "src/semver-__-version/compare_versions.md" 
  - test_solver_engine.pony : "src/semver-_-test-solver/test_solver_engine.md" 
  - test_utils_comparable_mixin.pony : "src/semver-_-test-utils/test_utils_comparable_mixin.md" 
  - signal_notify.pony : "src/signals/signal_notify.md" 
  - signal_handler.pony : "src/signals/signal_handler.md" 
  - sig.pony : "src/signals/sig.md" 
  - common_prefix.pony : "src/strings/common_prefix.md" 
  - readline_notify.pony : "src/term/readline_notify.md" 
  - readline.pony : "src/term/readline.md" 
  - ansi_term.pony : "src/term/ansi_term.md" 
  - ansi_notify.pony : "src/term/ansi_notify.md" 
  - ansi.pony : "src/term/ansi.md" 
  - timers.pony : "src/time/timers.md" 
  - timer_notify.pony : "src/time/timer_notify.md" 
  - timer.pony : "src/time/timer.md" 
  - time.pony : "src/time/time.md" 
  - posix_date.pony : "src/time/posix_date.md" 
  - nanos.pony : "src/time/nanos.md" 
